(() => {
  const $ = (id) => document.getElementById(id);
  const esc = (v) => String(v ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const state = { user:null, workspaces:[], tasks:[], waiting:[], calendar:[], loading:false };

  function message(id, text, error=false){ const el=$(id); if(!el)return; el.textContent=text||""; el.style.color=error?"#c83f55":""; }
  function show(session){ state.user=session?.user||null; $("authView")?.classList.toggle("hidden",!!state.user); $("appView")?.classList.toggle("hidden",!state.user); }
  function area(task){ return state.workspaces.find(w=>w.id===task.workspace_id)?.area||"personal"; }
  function workspaceId(name){ return state.workspaces.find(w=>w.area===name)?.id||null; }
  function areaName(name){ return ({dom_con:"Dom Con",eli_global:"ELI Global",personal:"Personal"}[name]||name); }
  function openTasks(){ return state.tasks.filter(t=>!["completed","cancelled"].includes(t.status)); }
  function score(t){ let s={p1:100,p2:70,p3:40,p4:20}[t.priority]||40; if(t.due_at){const d=(new Date(t.due_at)-new Date())/86400000;if(d<0)s+=50;else if(d<1)s+=30;else if(d<3)s+=15;} return s; }

  function taskRow(t){ const done=t.status==="completed"; const due=t.due_at?new Date(t.due_at).toLocaleDateString(undefined,{month:"short",day:"numeric"}):"No due date"; return `<div class="task-row"><input class="task-check" type="checkbox" data-task-toggle="${esc(t.id)}" ${done?"checked":""}><div><div class="task-title ${done?"done":""}">${esc(t.title)}</div><div class="task-meta">${esc(areaName(area(t)))} · ${esc(due)}</div></div><span class="task-pill">${esc(String(t.priority||"p3").toUpperCase())}</span></div>`; }
  function list(id, items, empty){ const el=$(id); if(el)el.innerHTML=items.length?items.map(taskRow).join(""):`<div class="empty-state">${esc(empty)}</div>`; }

  function render(){
    const open=openTasks(), ranked=[...open].sort((a,b)=>score(b)-score(a)), now=new Date(), today=now.toISOString().slice(0,10);
    const overdue=open.filter(t=>t.due_at&&new Date(t.due_at)<now), dueToday=open.filter(t=>t.due_at&&t.due_at.slice(0,10)===today);
    $("overdueCountDetail").textContent=overdue.length; $("dueTodayCountDetail").textContent=dueToday.length; $("waitingCountDetail").textContent=state.waiting.length;
    const next=ranked[0];
    $("briefing").innerHTML=[next?["▣",`${esc(next.title)} is your top priority`]:["✓","Your active task list is clear"],["⌑",state.calendar.length?`You have ${state.calendar.length} calendar event${state.calendar.length===1?"":"s"} today`:"Your calendar is clear today"],overdue.length?["✉",`${overdue.length} overdue item${overdue.length===1?" needs":"s need"} your attention`]:["✉","Nothing urgent is overdue"]].map(([i,t])=>`<div class="brief-line"><span class="brief-icon">${i}</span><span>${t}</span><span class="brief-chevron">›</span></div>`).join("");
    const nextEl=$("nextActionContent");
    if(next){ const ring=Math.max(40,Math.min(99,92-Math.max(0,overdue.length-1)*4)); const due=next.due_at?(new Date(next.due_at)<now?"Overdue":`Due ${new Date(next.due_at).toLocaleDateString(undefined,{month:"short",day:"numeric"})}`):"Start today"; nextEl.innerHTML=`<span class="flag-icon">⚑</span><div><div class="first-title">${esc(next.title)}</div><div class="first-meta"><span class="priority-text">${next.priority==="p1"?"High Priority":"Priority"}</span> · ${esc(due)}</div></div><div class="score-ring" style="--score:${ring}"><strong>${ring}</strong><small>SCORE</small></div>`; }
    else nextEl.innerHTML=`<span class="flag-icon">⚑</span><div><div class="first-title">Choose today's first win</div><div class="first-meta">Your task list is clear</div></div><div class="score-ring" style="--score:100"><strong>100</strong><small>SCORE</small></div>`;
    $("scheduleList").innerHTML=state.calendar.length?state.calendar.slice(0,3).map(e=>`<div class="calendar-item"><span class="calendar-time">${e.all_day?"All day":new Date(e.starts_at).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}</span><span class="calendar-title">${esc(e.title)}</span></div>`).join(""):`<div class="empty-state">No events today</div>`;
    list("allTasks",state.tasks.filter(t=>t.status!=="cancelled"),"Add your first task above."); list("domTasks",open.filter(t=>area(t)==="dom_con"),"No open Dom Con tasks."); list("eliTasks",open.filter(t=>area(t)==="eli_global"),"No open ELI Global tasks.");
    $("waitingList").innerHTML=state.waiting.length?state.waiting.map(w=>`<div class="task-row"><span>↗</span><div><div class="task-title">${esc(w.item)}</div><div class="task-meta">${esc(w.person_or_company||"Follow-up")}</div></div><span class="task-pill">OPEN</span></div>`).join(""):`<div class="empty-state">No open follow-ups.</div>`;
  }

  async function load(){ if(!state.user||state.loading)return; state.loading=true; $("sync").textContent="Syncing"; try{ const start=new Date();start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+1); const [w,t,wa,c]=await Promise.all([client.from("workspaces").select("*"),client.from("tasks").select("*").order("created_at",{ascending:false}),client.from("waiting_on").select("*").is("resolved_at",null).order("created_at",{ascending:false}),client.from("calendar_events_cache").select("*").gte("starts_at",start.toISOString()).lt("starts_at",end.toISOString()).order("starts_at")]); const bad=[w,t,wa,c].find(r=>r.error); if(bad)throw bad.error; state.workspaces=w.data||[];state.tasks=t.data||[];state.waiting=wa.data||[];state.calendar=c.data||[];render();$("sync").textContent="Synced"; }catch(e){console.error(e);$("sync").textContent="Retry";message("calendarStatus","Could not refresh data. Tap Sync to retry.",true);}finally{state.loading=false;} }
  async function signIn(e){e.preventDefault();const email=$("email").value.trim(),password=$("password").value;if(!email||!password)return message("authMsg","Enter both your email and password.",true);const b=$("signIn");b.disabled=true;b.textContent="Signing In…";message("authMsg","Signing in…");try{const {data,error}=await client.auth.signInWithPassword({email,password});if(error)throw error;show(data.session);message("authMsg","");await load();}catch(err){message("authMsg",err.message||"Sign in failed.",true);}finally{b.disabled=false;b.textContent="Sign In";}}
  async function signUp(){const email=$("email").value.trim(),password=$("password").value;if(!email||password.length<6)return message("authMsg","Enter a valid email and a password with at least 6 characters.",true);const {error}=await client.auth.signUp({email,password,options:{data:{display_name:"Emmit"}}});message("authMsg",error?error.message:"Account created. Check your email if confirmation is required.",!!error);}
  async function addTask(){const input=$("quickTitle"),title=input.value.trim();if(!title||!state.user)return;const {error}=await client.from("tasks").insert({owner_id:state.user.id,workspace_id:workspaceId($("quickArea").value),title,status:"planned",priority:$("quickPriority").value,source:"coffee_run"});if(error)return alert(error.message);input.value="";await load();}
  async function saveCapture(process){const input=$("aiInput"),raw=input.value.trim();if(!raw||!state.user)return;message("aiResult","Saving…");const {error}=await client.from("assistant_captures").insert({owner_id:state.user.id,raw_text:raw,status:process?"pending":"inbox",source:"coffee_run"});if(error)return message("aiResult",error.message,true);input.value="";message("aiResult",process?"Saved and queued for organization.":"Saved to your inbox.");}
  function tab(name){document.querySelectorAll(".page").forEach(p=>p.classList.toggle("active",p.id===name));document.querySelectorAll("[data-tab]").forEach(b=>b.classList.toggle("active",b.dataset.tab===name));window.scrollTo({top:0,behavior:"smooth"});}

  if(!window.supabase?.createClient){ document.addEventListener("DOMContentLoaded",()=>message("authMsg","Coffee Run could not load its secure connection. Refresh the page.",true)); return; }
  const client=window.supabase.createClient("https://hnvvvdibncwlplweeuod.supabase.co","sb_publishable_J-iF_-7VvAfXQKITPiNM_Q_cJUlokA1",{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storage:window.localStorage}});
  document.addEventListener("DOMContentLoaded",async()=>{
    const now=new Date(),h=now.getHours();$("greeting").innerHTML=`${h<12?"Good morning":h<18?"Good afternoon":"Good evening"},<br>Emmit.`;$("dateText").textContent=now.toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric"});
    $("authForm").addEventListener("submit",signIn);$("signUp").addEventListener("click",signUp);$("quickAdd").addEventListener("click",addTask);$("refreshAll").addEventListener("click",load);$("refreshCalendar").addEventListener("click",load);$("aiSubmit").addEventListener("click",()=>saveCapture(true));$("aiInboxOnly").addEventListener("click",()=>saveCapture(false));$("signOut").addEventListener("click",()=>client.auth.signOut());
    document.addEventListener("click",e=>{const t=e.target.closest("[data-tab]");if(t)tab(t.dataset.tab);const ai=e.target.closest("[data-ai-open]");if(ai)tab("ai");const p=e.target.closest("[data-prompt]");if(p){$("aiInput").value=p.dataset.prompt;$("aiInput").focus();}});
    document.addEventListener("change",async e=>{const cb=e.target.closest("[data-task-toggle]");if(!cb)return;await client.from("tasks").update({status:cb.checked?"completed":"planned",completed_at:cb.checked?new Date().toISOString():null}).eq("id",cb.dataset.taskToggle);await load();});
    try{const {data,error}=await client.auth.getSession();if(error)throw error;show(data.session);if(data.session)await load();}catch(e){show(null);message("authMsg","Coffee Run could not connect. Refresh and try again.",true);}client.auth.onAuthStateChange((_e,session)=>{show(session);if(session)setTimeout(load,0);});
  });
})();