import {createClient} from "https://esm.sh/@supabase/supabase-js@2";
const sb=createClient("https://hnvvvdibncwlplweeuod.supabase.co","sb_publishable_J-iF_-7VvAfXQKITPiNM_Q_cJUlokA1",{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storage:window.localStorage}});
let user,workspaces=[],tasks=[],waiting=[],notes=[],focus=null,calendarEvents=[],recommendedTask=null,focusInterval=null,focusSeconds=1500,focusRunning=false;
const $=id=>document.getElementById(id),esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
const areaOf=t=>workspaces.find(w=>w.id===t.workspace_id)?.area||"personal",areaLabel=a=>({dom_con:"Dom Con",personal:"Personal",eli_global:"ELI Global",second_brain:"Second Brain"}[a]||a),ws=a=>workspaces.find(w=>w.area===a)?.id||null,today=()=>new Date().toISOString().slice(0,10);
const sync=t=>$("sync").textContent=t||"Syncing…",synced=()=>$("sync").textContent="Synced";
const formatDuration=m=>m?`${m} min`:"25 min",relativeTime=d=>{const ms=new Date(d)-new Date(),mins=Math.round(Math.abs(ms)/60000);if(ms>0)return mins<60?`in ${mins} min`:`in ${Math.round(mins/60)} hr`;return mins<60?`${mins} min ago`:`${Math.round(mins/60)} hr ago`};
function taskScore(t){let s={p1:100,p2:70,p3:40,p4:20}[t.priority]||40;if(t.due_at){const d=(new Date(t.due_at)-new Date())/86400000;if(d<0)s+=50;else if(d<1)s+=30;else if(d<3)s+=15}if(t.estimated_minutes&&t.estimated_minutes<=45)s+=8;return s}
function row(t){return `<div class="task ${t.status==="completed"?"done":""}"><input type="checkbox" ${t.status==="completed"?"checked":""} onchange="toggleTask('${t.id}',this.checked)"><div class="task-main"><div class="task-title">${esc(t.title)}</div><div class="task-meta">${areaLabel(areaOf(t))}${t.project_name?" • "+esc(t.project_name):""}${t.due_at?" • "+new Date(t.due_at).toLocaleString():""}</div></div><span class="pill ${t.priority}">${String(t.priority||"p3").toUpperCase()}</span><button class="danger-link" onclick="deleteTask('${t.id}')">✕</button></div>`}
function list(id,items){$(id).innerHTML=items.length?items.map(row).join(""):'<div class="empty">Nothing here yet.</div>'}
function healthState(open,overdue){if(overdue>=2)return["risk","Needs action"];if(overdue===1||open>=8)return["warn","Watch closely"];return["","Healthy"]}
function renderCompanyHealth(open,overdue,area,prefix){const areaOpen=open.filter(t=>areaOf(t)===area),areaOverdue=overdue.filter(t=>areaOf(t)===area),[state,label]=healthState(areaOpen.length,areaOverdue.length),card=$(prefix+"Open").closest(".health-card");card.classList.remove("warn","risk");if(state)card.classList.add(state);$(prefix+"HealthText").textContent=label;$(prefix+"Open").textContent=areaOpen.length}
function renderBrief(open,overdue,ranked){const now=new Date(),nextEvent=calendarEvents.find(e=>new Date(e.starts_at)>now),lines=[];if(nextEvent)lines.push(["◷",`${esc(nextEvent.title)} starts ${relativeTime(nextEvent.starts_at)}.`]);else lines.push(["✓","Your calendar is clear for the rest of today."]);if(overdue.length)lines.push(["!",`<strong>${overdue.length} task${overdue.length===1?" is":"s are"} overdue.</strong> Clear the highest-priority item first.`]);else lines.push(["✓","Nothing is overdue."]);if(waiting.length)lines.push(["↗",`You are waiting on <strong>${waiting.length}</strong> follow-up${waiting.length===1?"":"s"}.`]);if(ranked[0])lines.push(["→",`I recommend <strong>${esc(ranked[0].title)}</strong> as your next move.`]);else lines.push(["✦","Your task list is clear. Use this space for strategic work."]);$("briefing").innerHTML=focus?.briefing||lines.map(([i,t])=>`<div class="brief-line"><span class="brief-icon">${i}</span><span>${t}</span></div>`).join("")}
function renderNextAction(task){recommendedTask=task||null;if(!task){$("nextActionContent").innerHTML='<h2>No urgent action</h2><p class="next-action-copy">Your active task list is clear. Set today\'s mission or capture the next meaningful outcome.</p>';$("startFocus").disabled=true;return}$("startFocus").disabled=false;const due=task.due_at?new Date(task.due_at):null,dueText=due?(due<new Date()?"Overdue":`Due ${due.toLocaleDateString(undefined,{month:"short",day:"numeric"})}`):"No deadline";$("nextActionContent").innerHTML=`<h2>${esc(task.title)}</h2><p class="next-action-copy">This is the strongest combination of priority, urgency, and ability to make progress now.</p><div class="next-meta"><span class="meta-chip">${String(task.priority||"p3").toUpperCase()} priority</span><span class="meta-chip">${formatDuration(task.estimated_minutes)}</span><span class="meta-chip">${dueText}</span><span class="meta-chip">${areaLabel(areaOf(task))}</span></div>`}
function renderTimeline(){const events=[];tasks.forEach(t=>{if(t.completed_at)events.push({at:t.completed_at,title:`Completed ${t.title}`,detail:areaLabel(areaOf(t))});else if(t.created_at)events.push({at:t.created_at,title:`Added ${t.title}`,detail:`${areaLabel(areaOf(t))} task`})});notes.forEach(n=>n.created_at&&events.push({at:n.created_at,title:`Saved ${n.title||"a note"}`,detail:"Second Brain"}));waiting.forEach(w=>w.created_at&&events.push({at:w.created_at,title:`Waiting on ${w.person_or_company}`,detail:w.item}));calendarEvents.forEach(e=>events.push({at:e.starts_at,title:e.title,detail:"Calendar event"}));events.sort((a,b)=>new Date(b.at)-new Date(a.at));$("timelineList").innerHTML=events.length?events.slice(0,7).map(e=>`<div class="timeline-item"><div class="timeline-time">${relativeTime(e.at)}</div><div class="timeline-track"><span class="timeline-dot"></span></div><div class="timeline-content"><strong>${esc(e.title)}</strong><small>${esc(e.detail)}</small></div></div>`).join(""):'<div class="empty">Activity will appear here as you use Executive OS.</div>'}
function render(){const open=tasks.filter(t=>!["completed","cancelled"].includes(t.status)),done=tasks.filter(t=>t.status==="completed").length,now=new Date(),todayStr=today(),overdue=open.filter(t=>t.due_at&&new Date(t.due_at)<now),dueToday=open.filter(t=>t.due_at&&t.due_at.slice(0,10)===todayStr),unscheduled=open.filter(t=>!t.due_at),ranked=[...open].sort((a,b)=>taskScore(b)-taskScore(a));
list("topTasks",ranked.slice(0,3));list("allTasks",tasks.filter(t=>t.status!=="cancelled"));list("domTasks",open.filter(t=>areaOf(t)==="dom_con"));list("eliTasks",open.filter(t=>areaOf(t)==="eli_global"));
$("waitingList").innerHTML=waiting.length?waiting.map(x=>`<div class="task"><div class="task-main"><div class="task-title">${esc(x.item)}</div><div class="task-meta">${esc(x.person_or_company)}${x.follow_up_at?" • follow up "+new Date(x.follow_up_at).toLocaleString():""}</div></div><button class="danger-link" onclick="resolveWaiting('${x.id}')">Done</button></div>`).join(""):'<div class="empty">Nothing waiting.</div>';
$("notesList").innerHTML=notes.length?notes.map(n=>`<div class="task"><div class="task-main"><div class="task-title">${esc(n.title||"Untitled")}</div><div class="task-meta">${esc(n.body)}</div></div><button class="danger-link" onclick="deleteNote('${n.id}')">✕</button></div>`).join(""):'<div class="empty">No notes captured.</div>';
$("scheduleList").innerHTML=calendarEvents.length?calendarEvents.map(e=>`<div class="schedule-item"><div class="schedule-time">${e.all_day?"All day":new Date(e.starts_at).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}</div><div><strong>${esc(e.title)}</strong>${e.location?`<div class="task-meta">${esc(e.location)}</div>`:""}<span class="source-badge">Calendar</span></div></div>`).join(""):'<div class="empty">No synced events yet.</div>';
["overdueCount","overdueCountDetail"].forEach(id=>$(id).textContent=overdue.length);["waitingCount","waitingCountDetail"].forEach(id=>$(id).textContent=waiting.length);["dueTodayCount","dueTodayCountDetail"].forEach(id=>$(id).textContent=dueToday.length);$("unscheduledCount").textContent=unscheduled.length;$("personalOpen").textContent=open.filter(t=>areaOf(t)==="personal").length;$("notesCount").textContent=notes.length;
renderCompanyHealth(open,overdue,"dom_con","dom");renderCompanyHealth(open,overdue,"eli_global","eli");
let score=Math.max(0,Math.min(100,85-overdue.length*8-waiting.filter(x=>x.follow_up_at&&new Date(x.follow_up_at)<now).length*5+Math.min(done,10)));$("scoreRing").style.setProperty("--score",score);$("scoreValue").textContent=score;$("scoreLabel").textContent=score>=85?"Excellent":score>=70?"Strong":score>=50?"Needs focus":"At risk";
renderBrief(open,overdue,ranked);renderNextAction(ranked[0]);renderTimeline();$("mission").value=focus?.mission||""}
async function load(){sync();const start=new Date();start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+1);const results=await Promise.all([sb.from("workspaces").select("*"),sb.from("tasks").select("*").order("created_at",{ascending:false}),sb.from("waiting_on").select("*").is("resolved_at",null).order("created_at",{ascending:false}),sb.from("notes").select("*").order("created_at",{ascending:false}),sb.from("daily_focus").select("*").eq("focus_date",today()).maybeSingle(),sb.from("calendar_events_cache").select("*").gte("starts_at",start.toISOString()).lt("starts_at",end.toISOString()).order("starts_at")]);const failed=results.find(x=>x.error);if(failed){alert(failed.error.message);return}workspaces=results[0].data||[];tasks=results[1].data||[];waiting=results[2].data||[];notes=results[3].data||[];focus=results[4].data;calendarEvents=results[5].data||[];render();synced()}
async function syncCalendars(force=false){if(!user)return;const key="calendarSyncAt:"+user.id,last=+(localStorage.getItem(key)||0);if(!force&&Date.now()-last<15*60*1000)return;$("calendarStatus").textContent="Syncing family calendar…";const {data,error}=await sb.functions.invoke("sync-calendars",{body:{}});if(error){$("calendarStatus").textContent="Calendar sync failed. Tap Refresh to retry.";console.error(error);return}localStorage.setItem(key,String(Date.now()));$("calendarStatus").textContent=`Updated ${data?.imported||0} calendar events.`}
async function setSession(s){user=s?.user;$("authView").classList.toggle("hidden",!!user);$("appView").classList.toggle("hidden",!user);if(user){$("userEmail").textContent=user.email;await syncCalendars(false);await load()}}
window.toggleTask=async(id,c)=>{sync();await sb.from("tasks").update({status:c?"completed":"planned",completed_at:c?new Date().toISOString():null}).eq("id",id);load()};window.deleteTask=async id=>{if(confirm("Delete task?")){await sb.from("tasks").delete().eq("id",id);load()}};window.resolveWaiting=async id=>{await sb.from("waiting_on").update({resolved_at:new Date().toISOString()}).eq("id",id);load()};window.deleteNote=async id=>{if(confirm("Delete note?")){await sb.from("notes").delete().eq("id",id);load()}};
async function addTask(detailed=false){const title=$(detailed?"taskTitle":"quickTitle").value.trim();if(!title)return;const area=$(detailed?"taskArea":"quickArea").value,payload={owner_id:user.id,workspace_id:ws(area),title,status:"planned",priority:$(detailed?"taskPriority":"quickPriority").value,source:"executive_os"};if(detailed){payload.project_name=$("taskProject").value.trim()||null;payload.due_at=$("taskDue").value?new Date($("taskDue").value).toISOString():null;payload.estimated_minutes=+$("taskMinutes").value||null}await sb.from("tasks").insert(payload);$(detailed?"taskTitle":"quickTitle").value="";load()}
$("quickAdd").onclick=()=>addTask(false);$("addDetailedTask").onclick=()=>addTask(true);$("refreshCalendar").onclick=async()=>{await syncCalendars(true);await load()};
$("saveMission").onclick=async()=>{const mission=$("mission").value.trim(),payload={owner_id:user.id,focus_date:today(),mission},{error}=await sb.from("daily_focus").upsert(payload,{onConflict:"owner_id,focus_date"});$("missionSaved").textContent=error?error.message:"Saved";if(!error)load()};
$("addWaiting").onclick=async()=>{const p=$("waitPerson").value.trim(),i=$("waitItem").value.trim();if(!p||!i)return;await sb.from("waiting_on").insert({owner_id:user.id,workspace_id:ws("personal"),person_or_company:p,item:i,follow_up_at:$("waitDate").value?new Date($("waitDate").value).toISOString():null});$("waitPerson").value="";$("waitItem").value="";load()};
$("addNote").onclick=async()=>{const b=$("noteBody").value.trim();if(!b)return;await sb.from("notes").insert({owner_id:user.id,workspace_id:ws("second_brain"),title:$("noteTitle").value.trim()||null,body:b,note_type:"general"});$("noteTitle").value="";$("noteBody").value="";load()};
$("signIn").onclick=async()=>{const button=$("signIn"),email=$("email").value.trim(),password=$("password").value;$("authMsg").textContent="Signing in…";button.disabled=true;const{error}=await sb.auth.signInWithPassword({email,password});button.disabled=false;$("authMsg").textContent=error?.message||"Signed in. Loading your dashboard…"};$("signUp").onclick=async()=>{const{error}=await sb.auth.signUp({email:$("email").value.trim(),password:$("password").value,options:{data:{display_name:"Emmit"}}});$("authMsg").textContent=error?.message||"Account created."};$("signOut").onclick=()=>sb.auth.signOut();$("moreSignOut").onclick=()=>sb.auth.signOut();
function switchTab(tab){document.querySelectorAll(".section").forEach(x=>x.classList.remove("active"));document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("active",x.dataset.tab===tab));const section=$(tab);if(section)section.classList.add("active");window.scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));
const openAI=()=>{$("aiPanel").classList.remove("hidden");setTimeout(()=>$("aiInput").focus(),100)};$("aiFab").onclick=openAI;document.querySelectorAll("[data-ai-open]").forEach(b=>b.onclick=openAI);$("aiClose").onclick=()=>$("aiPanel").classList.add("hidden");document.querySelectorAll(".ai-chip").forEach(c=>c.onclick=()=>{$("aiInput").value=c.dataset.prompt;$("aiInput").focus()});
async function saveCapture(process=true){const raw=$("aiInput").value.trim();if(!raw)return;$("aiResult").classList.remove("hidden");$("aiResult").textContent="Saving…";const {data,error}=await sb.from("assistant_captures").insert({owner_id:user.id,raw_text:raw,status:process?"pending":"inbox",source:"executive_os"}).select().single();$("aiResult").textContent=error?error.message:(process?"Captured and queued for routing.":"Saved to your inbox.");if(!error){$("aiInput").value="";return data}}
$("aiSubmit").onclick=()=>saveCapture(true);$("aiInboxOnly").onclick=()=>saveCapture(false);
function updateFocusTimer(){const m=Math.floor(focusSeconds/60),s=focusSeconds%60;$("focusTimer").textContent=`${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`}
function startTimer(){clearInterval(focusInterval);focusRunning=true;$("pauseFocus").textContent="Pause";focusInterval=setInterval(()=>{if(focusSeconds>0){focusSeconds--;updateFocusTimer()}else{clearInterval(focusInterval);focusRunning=false;$("pauseFocus").textContent="Restart"}},1000)}
$("startFocus").onclick=()=>{if(!recommendedTask)return;focusSeconds=Math.max(5,Number(recommendedTask.estimated_minutes)||25)*60;$("focusTitle").textContent=recommendedTask.title;$("focusMeta").innerHTML=`<span class="meta-chip">${areaLabel(areaOf(recommendedTask))}</span><span class="meta-chip">${String(recommendedTask.priority||"p3").toUpperCase()}</span><span class="meta-chip">${formatDuration(recommendedTask.estimated_minutes)}</span>`;$("focusMode").classList.remove("hidden");updateFocusTimer();startTimer()};
$("pauseFocus").onclick=()=>{if(focusRunning){clearInterval(focusInterval);focusRunning=false;$("pauseFocus").textContent="Resume"}else startTimer()};
$("closeFocus").onclick=()=>{clearInterval(focusInterval);focusRunning=false;$("focusMode").classList.add("hidden")};
$("completeFocus").onclick=async()=>{if(!recommendedTask)return;clearInterval(focusInterval);await sb.from("tasks").update({status:"completed",completed_at:new Date().toISOString()}).eq("id",recommendedTask.id);$("focusMode").classList.add("hidden");focusRunning=false;await load()};
const now=new Date(),h=now.getHours();$("daypart").textContent=h<12?"Good morning":h<18?"Good afternoon":"Good evening";$("dateText").textContent=now.toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric",year:"numeric"});
const{data:{session}}=await sb.auth.getSession();setSession(session);sb.auth.onAuthStateChange((_e,s)=>setSession(s));