(()=>{
const SUPABASE_URL='https://hnvvvdibncwlplweeuod.supabase.co';
const SUPABASE_KEY='sb_publishable_J-iF_-7VvAfXQKITPiNM_Q_cJUlokA1';
const client=window.supabase?.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storage:window.localStorage}});
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
let mode='today';
function range(){const start=new Date();start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+(mode==='today'?1:14));return{start,end};}
function formatTime(event){if(event.all_day)return'All day';const start=new Date(event.starts_at);const end=event.ends_at?new Date(event.ends_at):null;const first=start.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});return end?`${first} – ${end.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}`:first;}
function dayKey(date){return new Date(date).toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});}
function render(events){const list=$('calendarFullList');if(!list)return;if(!events.length){list.innerHTML=`<div class="empty-state">No calendar events in this range.</div>`;return;}const groups=new Map();for(const event of events){const key=dayKey(event.starts_at);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(event);}list.innerHTML=[...groups.entries()].map(([day,items])=>`<section class="calendar-day-group"><div class="calendar-day-title">${esc(day)}</div>${items.map(event=>`<article class="calendar-event-row"><div class="calendar-event-time">${esc(formatTime(event))}</div><div class="calendar-event-copy"><strong>${esc(event.title||'Untitled event')}</strong>${event.location?`<small>📍 ${esc(event.location)}</small>`:''}${event.description?`<small>${esc(event.description)}</small>`:''}</div></article>`).join('')}</section>`).join('');}
async function loadCalendar(){const status=$('calendarFullStatus');if(status)status.textContent='Refreshing calendar…';try{const{data:sessionData}=await client.auth.getSession();if(!sessionData.session)throw new Error('Sign in first.');const{start,end}=range();const{data,error}=await client.from('calendar_events_cache').select('*').gte('starts_at',start.toISOString()).lt('starts_at',end.toISOString()).order('starts_at');if(error)throw error;render(data||[]);if(status)status.textContent=`Showing ${mode==='today'?'today':'the next 14 days'} · ${data?.length||0} event${data?.length===1?'':'s'}`;}catch(error){if(status){status.textContent=error.message||'Could not load calendar.';status.style.color='#c83f55';}}}
function setMode(next){mode=next;$('calendarToday')?.classList.toggle('active',mode==='today');$('calendarUpcoming')?.classList.toggle('active',mode==='upcoming');loadCalendar();}
document.addEventListener('DOMContentLoaded',()=>{$('calendarToday')?.addEventListener('click',()=>setMode('today'));$('calendarUpcoming')?.addEventListener('click',()=>setMode('upcoming'));$('calendarRefresh')?.addEventListener('click',loadCalendar);document.addEventListener('click',event=>{if(event.target.closest('[data-menu-tab="calendar"]'))setTimeout(loadCalendar,0);});});
})();