import {createClient} from "https://esm.sh/@supabase/supabase-js@2";
const sb=createClient("https://hnvvvdibncwlplweeuod.supabase.co","sb_publishable_J-iF_-7VvAfXQKITPiNM_Q_cJUlokA1",{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storage:window.localStorage}});
const VAPID_PUBLIC_KEY="BLW9M-68Fmwx9SPqNkOEZIIti33vJF_XwMmWDIwkd_BsOaCCJnFrEK7LtOaztz27gDJJFFUkYWN8JXTlCvc-LKM";
const $=id=>document.getElementById(id);
const isStandalone=()=>window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true;
const isIOS=()=>/iphone|ipad|ipod/i.test(navigator.userAgent);
function urlBase64ToUint8Array(base64String){const padding='='.repeat((4-base64String.length%4)%4);const base64=(base64String+padding).replace(/-/g,'+').replace(/_/g,'/');const raw=atob(base64);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
function injectCard(){const grid=document.querySelector('#home .grid');if(!grid||$('notificationCard'))return;const card=document.createElement('div');card.id='notificationCard';card.className='card s12 notification-card';card.innerHTML=`<div class="section-head"><div><div class="eyebrow">Native Notifications</div><h2>Executive OS alerts</h2><p id="notificationStatus" class="muted">Checking this device…</p></div><span id="notificationBadge" class="today-chip">Setup</span></div><div class="notification-actions"><button id="enableNotifications" class="btn">Enable Notifications</button><button id="testNotification" class="btn secondary hidden">Send Test</button></div><p id="notificationHelp" class="footnote muted"></p>`;grid.insertBefore(card,grid.children[2]||null);$('enableNotifications').addEventListener('click',enableNotifications);$('testNotification').addEventListener('click',sendTest);refreshStatus()}
async function getRegistration(){if(!('serviceWorker' in navigator))throw new Error('Service workers are not supported on this device.');return navigator.serviceWorker.register('/sw.js')}
async function currentSubscription(){if(!('serviceWorker' in navigator))return null;const reg=await navigator.serviceWorker.getRegistration();return reg?reg.pushManager.getSubscription():null}
async function refreshStatus(){const status=$('notificationStatus'),badge=$('notificationBadge'),enable=$('enableNotifications'),test=$('testNotification'),help=$('notificationHelp');if(!status)return;
 if(!('Notification' in window)||!('PushManager' in window)||!('serviceWorker' in navigator)){status.textContent='Push notifications are not supported in this browser.';badge.textContent='Unavailable';enable.disabled=true;return}
 if(isIOS()&&!isStandalone()){status.textContent='Add Executive OS to your iPhone Home Screen before enabling notifications.';badge.textContent='Install first';enable.textContent='How to Install';help.textContent='Safari: tap Share, choose Add to Home Screen, then open Executive OS from the new icon.';return}
 const sub=await currentSubscription().catch(()=>null);if(Notification.permission==='granted'&&sub){status.textContent='Notifications are enabled on this device.';badge.textContent='Enabled';enable.textContent='Notifications Enabled';enable.disabled=true;test.classList.remove('hidden');help.textContent='Reminder alerts can appear even when Executive OS is closed.';return}
 if(Notification.permission==='denied'){status.textContent='Notification permission is blocked for Executive OS.';badge.textContent='Blocked';enable.textContent='Permission Blocked';enable.disabled=true;help.textContent='Open iPhone Settings, find Executive OS notifications, and allow them.';return}
 status.textContent='Enable alerts for reminder times, due items, and Chief of Staff follow-ups.';badge.textContent='Ready';enable.textContent='Enable Notifications';enable.disabled=false;test.classList.add('hidden');help.textContent='You will be asked once for permission.'}
async function enableNotifications(){const status=$('notificationStatus');try{if(isIOS()&&!isStandalone()){status.textContent='Open Safari Share, tap Add to Home Screen, then launch Executive OS from that icon.';return}const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('Notification permission was not granted.');const reg=await getRegistration();const sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64ToUint8Array(VAPID_PUBLIC_KEY)});const json=sub.toJSON();const {data:{session}}=await sb.auth.getSession();if(!session?.user)throw new Error('Please sign in again.');const {error}=await sb.from('push_subscriptions').upsert({owner_id:session.user.id,endpoint:json.endpoint,p256dh:json.keys.p256dh,auth:json.keys.auth,user_agent:navigator.userAgent,enabled:true,updated_at:new Date().toISOString()},{onConflict:'endpoint'});if(error)throw error;await refreshStatus()}catch(error){status.textContent=error?.message||'Could not enable notifications.'}}
async function sendTest(){const status=$('notificationStatus');status.textContent='Sending a test notification…';const {data,error}=await sb.functions.invoke('send-test-notification',{body:{}});if(error){status.textContent=error.message;return}status.textContent=data?.sent?`Test sent to ${data.sent} device${data.sent===1?'':'s'}.`:'No active device subscription was found.'}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',injectCard);else injectCard();
window.addEventListener('focus',()=>refreshStatus().catch(()=>{}));