import {createClient} from "https://esm.sh/@supabase/supabase-js@2";

const sb=createClient("https://hnvvvdibncwlplweeuod.supabase.co","sb_publishable_J-iF_-7VvAfXQKITPiNM_Q_cJUlokA1",{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storage:window.localStorage}});
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
const areaLabel=a=>({dom_con:"Dom Con",eli_global:"ELI Global",personal:"Personal"}[a]||a||"Personal");
let session=null,goals=[],tasks=[],workspaceId=null,editingId=null,linkingGoalId=null;

function decodeGoal(note){try{const d=JSON.parse(note.body||"{}");return{id:note.id,title:note.title||"Untitled goal",area:d.area||"personal",target:d.target||"",deadline:d.deadline||null,progress:Math.max(0,Math.min(100,Number(d.progress)||0)),status:d.status||"active",milestones:Array.isArray(d.milestones)?d.milestones:[],created_at:note.created_at}}catch{return null}}
function encodeGoal(g){return JSON.stringify({area:g.area,target:g.target,deadline:g.deadline,progress:g.progress,status:g.status,milestones:g.milestones||[]})}
function taskGoalId(t){return t.executive_context?.goal_id||null}
function linkedTasks(g){const title=g.title.toLowerCase();return tasks.filter(t=>taskGoalId(t)===g.id||(!taskGoalId(t)&&String(t.project_name||"").toLowerCase()===title))}
function derivedProgress(g){const linked=linkedTasks(g),ms=g.milestones||[];if(linked.length)return Math.round(linked.filter(t=>t.status==="completed").length/linked.length*100);if(ms.length)return Math.round(ms.filter(m=>m.done).length/ms.length*100);return g.progress}
function statusLabel(g){if(g.status==="completed")return"Completed";if(g.deadline&&new Date(g.deadline+"T23:59:59")<new Date())return"At risk";if(derivedProgress(g)>=75)return"On track";return"Active"}

function install(){
  const section=document.getElementById("goals");if(!section||section.dataset.sprint4)return;section.dataset.sprint4="true";
  section.innerHTML=`<div class="page-title"><div class="eyebrow">Strategic Planning · Sprint 4</div><h2>Goals</h2><p class="task-meta">Turn priorities into measurable outcomes, milestones, and linked execution.</p></div><div id="goalSummary" class="goal-summary"></div><div class="goal-layout"><div id="goalList" class="goal-list"></div><div class="card goal-form"><div class="eyebrow" id="goalFormLabel">Create a goal</div><h3 id="goalFormHeading">Define the outcome</h3><input id="goalTitle" class="field" placeholder="Goal title"><select id="goalArea" class="field"><option value="dom_con">Dom Con</option><option value="eli_global">ELI Global</option><option value="personal">Personal</option></select><input id="goalTarget" class="field" placeholder="Success measure (example: Sign 10 customers)"><input id="goalDeadline" class="field" type="date"><div class="goal-form-actions"><button id="saveGoal" class="btn full">Create Goal</button><button id="cancelGoalEdit" class="btn secondary hidden">Cancel</button></div><p class="muted footnote">Tasks created or selected from a goal retain a durable goal link.</p></div></div><div id="goalTaskModal" class="goal-modal hidden" role="dialog" aria-modal="true" aria-labelledby="goalTaskModalTitle"><div class="goal-modal-card"><div class="goal-modal-head"><div><div class="eyebrow">Link existing work</div><h3 id="goalTaskModalTitle">Choose tasks</h3></div><button class="btn secondary compact" id="closeGoalTaskModal">Close</button></div><input id="goalTaskSearch" class="field" placeholder="Search active tasks"><div id="goalTaskPicker" class="goal-task-picker"></div><div class="goal-modal-actions"><button class="btn full" id="saveGoalTaskLinks">Save task links</button></div></div></div>`;
  const style=document.createElement("style");style.textContent=`.goal-layout{display:grid;grid-template-columns:minmax(0,1.7fr) minmax(280px,.8fr);gap:16px}.goal-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:16px}.goal-stat,.goal-card{border:1px solid rgba(125,170,230,.16);background:rgba(8,25,50,.35);border-radius:17px}.goal-stat{padding:13px}.goal-stat strong,.goal-stat small{display:block}.goal-stat strong{font-size:1.35rem}.goal-stat small,.goal-meta,.goal-linked{color:var(--muted,#9eb1cc)}.goal-card{padding:16px;margin-bottom:12px}.goal-head{display:flex;gap:12px;align-items:flex-start}.goal-head>div{flex:1}.goal-head h3{margin:2px 0 5px}.goal-badge{font-size:.72rem;padding:5px 8px;border-radius:999px;background:rgba(87,139,225,.16)}.goal-meta,.goal-linked{font-size:.78rem}.goal-progress{height:9px;border-radius:99px;background:rgba(125,170,230,.12);overflow:hidden;margin:13px 0 8px}.goal-progress span{display:block;height:100%;background:linear-gradient(90deg,#4d8df7,#63d6b4)}.goal-actions,.goal-form-actions,.milestone-add{display:flex;gap:8px;align-items:center;margin-top:12px;flex-wrap:wrap}.goal-actions input{width:82px}.milestones{margin-top:14px;padding-top:12px;border-top:1px solid rgba(125,170,230,.12)}.milestone{display:flex;gap:8px;align-items:center;padding:6px 0}.milestone span{flex:1}.milestone.done span{text-decoration:line-through;opacity:.65}.milestone-add input{flex:1;min-width:170px}.goal-linked{margin-top:10px}.goal-empty{padding:24px;text-align:center;color:var(--muted,#9eb1cc)}.goal-modal{position:fixed;inset:0;z-index:1000;background:rgba(2,10,24,.78);display:grid;place-items:center;padding:18px}.goal-modal.hidden{display:none}.goal-modal-card{width:min(680px,100%);max-height:82vh;overflow:auto;border:1px solid rgba(125,170,230,.2);background:#0b1d38;border-radius:20px;padding:18px;box-shadow:0 24px 70px rgba(0,0,0,.45)}.goal-modal-head,.goal-task-row{display:flex;gap:12px;align-items:center}.goal-modal-head>div{flex:1}.goal-task-picker{margin-top:12px}.goal-task-row{padding:11px 4px;border-bottom:1px solid rgba(125,170,230,.12)}.goal-task-row>div{flex:1}.goal-task-row strong,.goal-task-row small{display:block}.goal-task-row small{color:var(--muted,#9eb1cc);margin-top:3px}.goal-modal-actions{margin-top:14px}@media(max-width:760px){.goal-layout{grid-template-columns:1fr}.goal-summary{grid-template-columns:repeat(2,1fr)}}`;document.head.appendChild(style);
  document.getElementById("saveGoal").onclick=saveGoal;document.getElementById("cancelGoalEdit").onclick=resetForm;document.getElementById("closeGoalTaskModal").onclick=closeTaskPicker;document.getElementById("saveGoalTaskLinks").onclick=saveTaskLinks;document.getElementById("goalTaskSearch").oninput=renderTaskPicker;
}

function render(){
  const active=goals.filter(g=>g.status!=="completed"),done=goals.filter(g=>g.status==="completed"),atRisk=active.filter(g=>g.deadline&&new Date(g.deadline+"T23:59:59")<new Date()),avg=goals.length?Math.round(goals.reduce((s,g)=>s+derivedProgress(g),0)/goals.length):0;
  const summary=document.getElementById("goalSummary");if(summary)summary.innerHTML=[[active.length,"Active"],[done.length,"Completed"],[atRisk.length,"At risk"],[`${avg}%`,"Average progress"]].map(([v,l])=>`<div class="goal-stat"><strong>${v}</strong><small>${l}</small></div>`).join("");
  const list=document.getElementById("goalList");if(!list)return;
  list.innerHTML=goals.length?goals.map(g=>{const p=derivedProgress(g),linked=linkedTasks(g),completed=linked.filter(t=>t.status==="completed").length,ms=g.milestones||[];return `<article class="goal-card"><div class="goal-head"><div><div class="eyebrow">${esc(areaLabel(g.area))}</div><h3>${esc(g.title)}</h3><div class="goal-meta">${esc(g.target||"No success measure set")}${g.deadline?` · Target ${new Date(g.deadline+"T12:00:00").toLocaleDateString()}`:""}</div></div><span class="goal-badge">${esc(statusLabel(g))}</span></div><div class="goal-progress"><span style="width:${p}%"></span></div><div class="goal-meta"><strong>${p}% complete</strong>${linked.length?` · ${completed} of ${linked.length} linked tasks done`:ms.length?` · ${ms.filter(m=>m.done).length} of ${ms.length} milestones done`:" · Manual progress"}</div><div class="goal-actions"><button class="btn secondary compact" onclick="window.editGoal('${g.id}')">Edit</button><button class="btn secondary compact" onclick="window.createGoalTask('${g.id}')">Add task</button><button class="btn secondary compact" onclick="window.openGoalTaskPicker('${g.id}')">Link tasks</button><input class="field" type="number" min="0" max="100" value="${g.progress}" aria-label="Manual progress" onchange="window.updateGoalProgress('${g.id}',this.value)"><button class="btn secondary compact" onclick="window.completeGoal('${g.id}')">${g.status==="completed"?"Reopen":"Complete"}</button><button class="danger-link" onclick="window.deleteGoal('${g.id}')">Delete</button></div><div class="milestones"><div class="eyebrow">Milestones</div>${ms.map(m=>`<div class="milestone ${m.done?"done":""}"><input type="checkbox" ${m.done?"checked":""} onchange="window.toggleMilestone('${g.id}','${m.id}')"><span>${esc(m.title)}</span><button class="danger-link" onclick="window.deleteMilestone('${g.id}','${m.id}')">Remove</button></div>`).join("")}<div class="milestone-add"><input id="milestone-${g.id}" class="field" placeholder="Add a milestone"><button class="btn secondary compact" onclick="window.addMilestone('${g.id}')">Add</button></div></div><div class="goal-linked">${linked.length?`${linked.length} task${linked.length===1?"":"s"} linked to this goal.`:"No linked tasks yet."}</div></article>`}).join(""):`<div class="goal-empty card">No strategic goals yet. Create one outcome that would materially improve your next quarter.</div>`;
}

function taskMatchesSearch(t,q){return !q||[t.title,t.description,t.related_person,t.project_name].some(v=>String(v||"").toLowerCase().includes(q))}
function renderTaskPicker(){
  const goal=goals.find(g=>g.id===linkingGoalId),box=document.getElementById("goalTaskPicker");if(!goal||!box)return;
  const q=document.getElementById("goalTaskSearch").value.trim().toLowerCase();
  const visible=tasks.filter(t=>!["completed","cancelled"].includes(t.status)&&taskMatchesSearch(t,q));
  box.innerHTML=visible.length?visible.map(t=>{const current=taskGoalId(t),checked=current===goal.id||(!current&&String(t.project_name||"").toLowerCase()===goal.title.toLowerCase()),other=current&&current!==goal.id?goals.find(g=>g.id===current):null;return `<label class="goal-task-row"><input type="checkbox" data-task-link="${t.id}" ${checked?"checked":""}><div><strong>${esc(t.title)}</strong><small>${esc(String(t.priority||"p3").toUpperCase())}${other?` · Currently linked to ${esc(other.title)}`:""}</small></div></label>`}).join(""):`<div class="goal-empty">No matching active tasks.</div>`;
}
function closeTaskPicker(){linkingGoalId=null;document.getElementById("goalTaskModal")?.classList.add("hidden")}
window.openGoalTaskPicker=id=>{const g=goals.find(x=>x.id===id);if(!g)return;linkingGoalId=id;document.getElementById("goalTaskModalTitle").textContent=`Link tasks to ${g.title}`;document.getElementById("goalTaskSearch").value="";document.getElementById("goalTaskModal").classList.remove("hidden");renderTaskPicker()};
async function saveTaskLinks(){
  const goal=goals.find(g=>g.id===linkingGoalId);if(!goal)return;
  const selected=new Set([...document.querySelectorAll("[data-task-link]:checked")].map(x=>x.dataset.taskLink));
  const updates=tasks.filter(t=>!["completed","cancelled"].includes(t.status)).map(t=>{const current=taskGoalId(t),legacy=!current&&String(t.project_name||"").toLowerCase()===goal.title.toLowerCase(),shouldLink=selected.has(t.id),wasLinked=current===goal.id||legacy;if(shouldLink===wasLinked)return null;const ctx={...(t.executive_context||{})};if(shouldLink){ctx.goal_id=goal.id;ctx.goal_title=goal.title}else{delete ctx.goal_id;delete ctx.goal_title}return sb.from("tasks").update({executive_context:ctx}).eq("owner_id",session.user.id).eq("id",t.id)}).filter(Boolean);
  const results=await Promise.all(updates),failed=results.find(r=>r.error);if(failed?.error){alert(failed.error.message);return}closeTaskPicker();await load();
}

async function load(){if(!session?.user)return;const[nr,tr,wr]=await Promise.all([sb.from("notes").select("*").eq("owner_id",session.user.id).eq("note_type","strategic_goal").order("created_at",{ascending:false}),sb.from("tasks").select("*").eq("owner_id",session.user.id).neq("status","cancelled"),sb.from("workspaces").select("id,area").eq("area","second_brain").maybeSingle()]);if(nr.error||tr.error||wr.error){console.error("Strategic Goals",nr.error||tr.error||wr.error);return}workspaceId=wr.data?.id||null;goals=(nr.data||[]).map(decodeGoal).filter(Boolean);tasks=tr.data||[];render()}
function resetForm(){editingId=null;["goalTitle","goalTarget","goalDeadline"].forEach(id=>document.getElementById(id).value="");document.getElementById("goalArea").value="dom_con";document.getElementById("goalFormLabel").textContent="Create a goal";document.getElementById("goalFormHeading").textContent="Define the outcome";document.getElementById("saveGoal").textContent="Create Goal";document.getElementById("cancelGoalEdit").classList.add("hidden")}
async function saveGoal(){const title=document.getElementById("goalTitle").value.trim();if(!title)return;const current=goals.find(g=>g.id===editingId);const goal={...(current||{}),area:document.getElementById("goalArea").value,target:document.getElementById("goalTarget").value.trim(),deadline:document.getElementById("goalDeadline").value||null,progress:current?.progress||0,status:current?.status||"active",milestones:current?.milestones||[]};const q=editingId?sb.from("notes").update({title,body:encodeGoal(goal)}).eq("id",editingId):sb.from("notes").insert({owner_id:session.user.id,workspace_id:workspaceId,title,body:encodeGoal(goal),note_type:"strategic_goal"});const{error}=await q;if(error){alert(error.message);return}resetForm();load()}
async function persist(g){const{error}=await sb.from("notes").update({body:encodeGoal(g)}).eq("id",g.id);if(error)alert(error.message);await load()}
window.editGoal=id=>{const g=goals.find(x=>x.id===id);if(!g)return;editingId=id;document.getElementById("goalTitle").value=g.title;document.getElementById("goalArea").value=g.area;document.getElementById("goalTarget").value=g.target;document.getElementById("goalDeadline").value=g.deadline||"";document.getElementById("goalFormLabel").textContent="Edit goal";document.getElementById("goalFormHeading").textContent="Update the outcome";document.getElementById("saveGoal").textContent="Save Changes";document.getElementById("cancelGoalEdit").classList.remove("hidden");document.getElementById("goalTitle").focus()};
window.updateGoalProgress=(id,v)=>{const g=goals.find(x=>x.id===id);if(g){g.progress=Math.max(0,Math.min(100,Number(v)||0));persist(g)}};
window.completeGoal=id=>{const g=goals.find(x=>x.id===id);if(g){g.status=g.status==="completed"?"active":"completed";if(g.status==="completed")g.progress=100;persist(g)}};
window.addMilestone=id=>{const g=goals.find(x=>x.id===id),input=document.getElementById(`milestone-${id}`),title=input?.value.trim();if(g&&title){g.milestones.push({id:crypto.randomUUID(),title,done:false});persist(g)}};
window.toggleMilestone=(id,mid)=>{const g=goals.find(x=>x.id===id),m=g?.milestones.find(x=>x.id===mid);if(m){m.done=!m.done;persist(g)}};
window.deleteMilestone=(id,mid)=>{const g=goals.find(x=>x.id===id);if(g){g.milestones=g.milestones.filter(x=>x.id!==mid);persist(g)}};
window.createGoalTask=async id=>{const g=goals.find(x=>x.id===id);if(!g)return;const title=prompt(`Task for “${g.title}”:`);if(!title?.trim())return;const payload={owner_id:session.user.id,workspace_id:null,title:title.trim(),description:`Linked to strategic goal: ${g.title}`,status:"planned",priority:"p3",source:"strategic_goals",executive_context:{goal_id:g.id,goal_title:g.title}};const{error}=await sb.from("tasks").insert(payload);if(error)alert(error.message);else load()};
window.deleteGoal=async id=>{if(confirm("Delete this goal? Linked tasks will remain.")){await sb.from("notes").delete().eq("id",id);load()}};
async function start(){const{data:{session:s}}=await sb.auth.getSession();session=s;if(!session?.user)return;install();await load();setInterval(load,60000)}
sb.auth.onAuthStateChange((_e,s)=>{session=s;if(s?.user)setTimeout(start,250)});if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start);else start();