import {createClient} from "https://esm.sh/@supabase/supabase-js@2";

const sb=createClient("https://hnvvvdibncwlplweeuod.supabase.co","sb_publishable_J-iF_-7VvAfXQKITPiNM_Q_cJUlokA1",{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storage:window.localStorage}});
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
const areaLabel=a=>({dom_con:"Dom Con",eli_global:"ELI Global",personal:"Personal"}[a]||a||"Personal");
let session=null,goals=[],tasks=[],workspaceId=null;

function decodeGoal(note){
  try{const data=JSON.parse(note.body||"{}");return{id:note.id,title:note.title||"Untitled goal",area:data.area||"personal",target:data.target||"",deadline:data.deadline||null,progress:Math.max(0,Math.min(100,Number(data.progress)||0)),status:data.status||"active",created_at:note.created_at}}
  catch{return null}
}
function encodeGoal(goal){return JSON.stringify({area:goal.area,target:goal.target,deadline:goal.deadline,progress:goal.progress,status:goal.status})}
function linkedTasks(goal){const title=goal.title.toLowerCase();return tasks.filter(t=>String(t.project_name||"").toLowerCase()===title)}
function derivedProgress(goal){const linked=linkedTasks(goal);if(!linked.length)return goal.progress;return Math.round(linked.filter(t=>t.status==="completed").length/linked.length*100)}
function statusLabel(goal){if(goal.status==="completed")return"Completed";if(goal.deadline&&new Date(goal.deadline)<new Date())return"At risk";if(derivedProgress(goal)>=75)return"On track";return"Active"}
function install(){
  const section=document.getElementById("goals");if(!section||section.dataset.sprint4)return;section.dataset.sprint4="true";
  section.innerHTML=`<div class="page-title"><div class="eyebrow">Strategic Planning · Sprint 4</div><h2>Goals</h2><p class="task-meta">Turn priorities into measurable outcomes and keep execution connected to the work.</p></div><div id="goalSummary" class="goal-summary"></div><div class="goal-layout"><div><div id="goalList" class="goal-list"></div></div><div class="card goal-form"><div class="eyebrow">Create a goal</div><h3>Define the outcome</h3><input id="goalTitle" class="field" placeholder="Goal title"><select id="goalArea" class="field"><option value="dom_con">Dom Con</option><option value="eli_global">ELI Global</option><option value="personal">Personal</option></select><input id="goalTarget" class="field" placeholder="Success measure (example: Sign 10 customers)"><input id="goalDeadline" class="field" type="date"><button id="addGoal" class="btn full">Create Goal</button><p class="muted footnote">Tasks with a Project matching the goal title automatically roll into progress.</p></div></div>`;
  const style=document.createElement("style");style.textContent=`.goal-layout{display:grid;grid-template-columns:minmax(0,1.7fr) minmax(280px,.8fr);gap:16px}.goal-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:16px}.goal-stat,.goal-card{border:1px solid rgba(125,170,230,.16);background:rgba(8,25,50,.35);border-radius:17px}.goal-stat{padding:13px}.goal-stat strong,.goal-stat small{display:block}.goal-stat strong{font-size:1.35rem}.goal-stat small{color:var(--muted,#9eb1cc);margin-top:3px}.goal-card{padding:16px;margin-bottom:12px}.goal-head{display:flex;gap:12px;align-items:flex-start}.goal-head>div{flex:1}.goal-head h3{margin:2px 0 5px}.goal-badge{font-size:.72rem;padding:5px 8px;border-radius:999px;background:rgba(87,139,225,.16)}.goal-meta{font-size:.78rem;color:var(--muted,#9eb1cc)}.goal-progress{height:9px;border-radius:99px;background:rgba(125,170,230,.12);overflow:hidden;margin:13px 0 8px}.goal-progress span{display:block;height:100%;background:linear-gradient(90deg,#4d8df7,#63d6b4)}.goal-actions{display:flex;gap:8px;align-items:center;margin-top:12px}.goal-actions input{width:82px}.goal-linked{margin-top:10px;font-size:.78rem;color:var(--muted,#9eb1cc)}.goal-empty{padding:24px;text-align:center;color:var(--muted,#9eb1cc)}@media(max-width:760px){.goal-layout{grid-template-columns:1fr}.goal-summary{grid-template-columns:repeat(2,1fr)}}`;document.head.appendChild(style);
  document.getElementById("addGoal").onclick=addGoal;
}
function render(){
  const active=goals.filter(g=>g.status!=="completed"),done=goals.filter(g=>g.status==="completed"),atRisk=active.filter(g=>g.deadline&&new Date(g.deadline)<new Date()),avg=goals.length?Math.round(goals.reduce((s,g)=>s+derivedProgress(g),0)/goals.length):0;
  const summary=document.getElementById("goalSummary");if(summary)summary.innerHTML=[[active.length,"Active"],[done.length,"Completed"],[atRisk.length,"At risk"],[`${avg}%`,"Average progress"]].map(([v,l])=>`<div class="goal-stat"><strong>${v}</strong><small>${l}</small></div>`).join("");
  const list=document.getElementById("goalList");if(!list)return;
  list.innerHTML=goals.length?goals.map(g=>{const progress=derivedProgress(g),linked=linkedTasks(g),completed=linked.filter(t=>t.status==="completed").length;return `<article class="goal-card"><div class="goal-head"><div><div class="eyebrow">${esc(areaLabel(g.area))}</div><h3>${esc(g.title)}</h3><div class="goal-meta">${esc(g.target||"No success measure set")}${g.deadline?` · Target ${new Date(g.deadline+"T12:00:00").toLocaleDateString()}`:""}</div></div><span class="goal-badge">${esc(statusLabel(g))}</span></div><div class="goal-progress"><span style="width:${progress}%"></span></div><div class="goal-meta"><strong>${progress}% complete</strong>${linked.length?` · ${completed} of ${linked.length} linked tasks done`:" · Manual progress"}</div><div class="goal-actions"><input class="field" type="number" min="0" max="100" value="${g.progress}" aria-label="Manual progress" onchange="window.updateGoalProgress('${g.id}',this.value)"><button class="btn secondary compact" onclick="window.completeGoal('${g.id}')">${g.status==="completed"?"Reopen":"Complete"}</button><button class="danger-link" onclick="window.deleteGoal('${g.id}')">Delete</button></div><div class="goal-linked">Link tasks by setting their Project field to “${esc(g.title)}”.</div></article>`}).join(""):`<div class="goal-empty card">No strategic goals yet. Create one outcome that would materially improve your next quarter.</div>`;
}
async function load(){if(!session?.user)return;const [nr,tr,wr]=await Promise.all([sb.from("notes").select("*").eq("owner_id",session.user.id).eq("note_type","strategic_goal").order("created_at",{ascending:false}),sb.from("tasks").select("*").eq("owner_id",session.user.id).neq("status","cancelled"),sb.from("workspaces").select("id,area").eq("area","second_brain").maybeSingle()]);if(nr.error||tr.error||wr.error){console.error("Strategic Goals",nr.error||tr.error||wr.error);return}workspaceId=wr.data?.id||null;goals=(nr.data||[]).map(decodeGoal).filter(Boolean);tasks=tr.data||[];render()}
async function addGoal(){const title=document.getElementById("goalTitle").value.trim();if(!title)return;const goal={area:document.getElementById("goalArea").value,target:document.getElementById("goalTarget").value.trim(),deadline:document.getElementById("goalDeadline").value||null,progress:0,status:"active"};const{error}=await sb.from("notes").insert({owner_id:session.user.id,workspace_id:workspaceId,title,body:encodeGoal(goal),note_type:"strategic_goal"});if(error){alert(error.message);return}document.getElementById("goalTitle").value="";document.getElementById("goalTarget").value="";document.getElementById("goalDeadline").value="";load()}
window.updateGoalProgress=async(id,value)=>{const goal=goals.find(g=>g.id===id);if(!goal)return;goal.progress=Math.max(0,Math.min(100,Number(value)||0));await sb.from("notes").update({body:encodeGoal(goal)}).eq("id",id);load()};
window.completeGoal=async id=>{const goal=goals.find(g=>g.id===id);if(!goal)return;goal.status=goal.status==="completed"?"active":"completed";if(goal.status==="completed")goal.progress=100;await sb.from("notes").update({body:encodeGoal(goal)}).eq("id",id);load()};
window.deleteGoal=async id=>{if(confirm("Delete this goal?")){await sb.from("notes").delete().eq("id",id);load()}};
async function start(){const{data:{session:s}}=await sb.auth.getSession();session=s;if(!session?.user)return;install();await load();setInterval(load,60000)}
sb.auth.onAuthStateChange((_e,s)=>{session=s;if(s?.user)setTimeout(start,250)});if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start);else start();
