(()=>{
  const $=id=>document.getElementById(id);
  const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;
  let recognition=null,listening=false,baseText='';
  const status=text=>{const el=$('voiceStatus');if(el)el.textContent=text};
  const setListening=on=>{listening=on;['voiceInput','voiceInputInline'].forEach(id=>$(id)?.classList.toggle('listening',on));const main=$('voiceInput');if(main){const label=main.querySelector('strong');if(label)label.textContent=on?'Listening…':'Talk to Coffee Run'}};
  const speak=text=>{if(!('speechSynthesis'in window)||!text)return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text.replace(/\s+/g,' ').trim());u.rate=.98;u.pitch=1;u.lang='en-US';window.speechSynthesis.speak(u)};
  const clean=text=>text.replace(/^\s*(hey\s+)?coffee\s+run[,:]?\s*/i,'').trim();
  const start=()=>{if(!Recognition){status('Voice entry is not supported here. You can still use the iPhone keyboard microphone.');return}if(listening){recognition?.stop();return}const input=$('aiInput');baseText=input?.value.trim()||'';recognition=new Recognition();recognition.lang='en-US';recognition.continuous=false;recognition.interimResults=true;recognition.maxAlternatives=1;recognition.onstart=()=>{setListening(true);status('Listening… say a reminder, task, follow-up, or note.')};recognition.onresult=e=>{let interim='',final='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0].transcript;if(e.results[i].isFinal)final+=t;else interim+=t}const spoken=clean(final||interim);if(input)input.value=[baseText,spoken].filter(Boolean).join(baseText?' ':'');status(final?'Captured. Review it, then tap Save & Organize.':'Listening… '+spoken)};recognition.onerror=e=>{setListening(false);status(e.error==='not-allowed'?'Microphone permission was denied. Allow microphone access in Safari settings.':'Voice input stopped. Tap the microphone to try again.')};recognition.onend=()=>{setListening(false);if(!$('aiInput')?.value.trim())status('Tap the microphone and speak naturally.')};try{recognition.start()}catch{setListening(false);status('Voice input could not start. Tap again.')}};
  const readBriefing=()=>{const lines=[...document.querySelectorAll('#briefing .brief-line')].map(x=>x.textContent.replace('›','').trim());const next=$('nextActionContent')?.textContent.trim();const text=[lines.length?'Here is your Coffee Run briefing. '+lines.join('. '):'',next?'Your first move is '+next:''].filter(Boolean).join('. ');if(!text){status('Your briefing is not ready yet. Sync Coffee Run first.');return}status('Reading your briefing aloud.');speak(text)};
  document.addEventListener('DOMContentLoaded',()=>{$('voiceInput')?.addEventListener('click',start);$('voiceInputInline')?.addEventListener('click',start);$('readBriefing')?.addEventListener('click',readBriefing);const result=$('aiResult');if(result)new MutationObserver(()=>{const text=result.textContent.trim();if(/saved|queued|organized|inbox/i.test(text)){speak(text);status(text)}}).observe(result,{childList:true,characterData:true,subtree:true})});
})();