begin;
do $$
declare owner uuid; req uuid; action uuid; h text; res jsonb; n int;
begin
  select owner_id into owner from public.assistant_requests order by created_at limit 1;
  if owner is null then raise exception 'No test owner'; end if;
  insert into public.assistant_requests(owner_id,thread_id,message,status,source) values(owner,'approval-sql-test','Diagnostic fixture','processing','coffee_run_diagnostic') returning id into req;
  res=public.coach_finalize_request(owner,req,'awaiting_approval','Test only','diagnostic_success','{"summary":"test"}','[]');
  action=(res->'approval'->>'id')::uuid;h=res->'approval'->>'proposal_hash';
  begin perform public.coach_decide_action(gen_random_uuid(),action,h,'approve');raise exception 'Cross-owner accepted';exception when no_data_found then null;end;
  begin perform public.coach_decide_action(owner,action,repeat('0',64),'approve');raise exception 'Stale hash accepted';exception when invalid_parameter_value then null;end;
  res=public.coach_decide_action(owner,action,h,'approve');
  if res->'approval'->>'execution_status'<>'succeeded' then raise exception 'Approval failed';end if;
  res=public.coach_decide_action(owner,action,h,'approve');
  if not (res->>'idempotent_replay')::boolean or (res->'approval'->>'execution_attempts')::int<>1 then raise exception 'Duplicate executed';end if;
  res=public.coach_decide_action(owner,action,h,'decline');
  if res->'approval'->>'status'<>'approved' then raise exception 'Decision changed after completion';end if;
  select count(*) into n from public.assistant_action_events where action_id=action;
  if n<>3 then raise exception 'Unexpected event count %',n;end if;
  if has_table_privilege('authenticated','public.assistant_actions','UPDATE') or has_table_privilege('authenticated','public.assistant_actions','INSERT') or has_table_privilege('anon','public.assistant_actions','SELECT') then raise exception 'Unsafe table grants';end if;
  if has_function_privilege('authenticated','public.coach_decide_action(uuid,uuid,text,text)','EXECUTE') then raise exception 'Unsafe RPC grant';end if;
  perform set_config('request.jwt.claim.sub',owner::text,true);
  execute 'set local role authenticated';
  select count(*) into n from public.assistant_actions where id=action;
  if n<>1 then raise exception 'Owner could not read action';end if;
  perform set_config('request.jwt.claim.sub',gen_random_uuid()::text,true);
  select count(*) into n from public.assistant_actions where id=action;
  if n<>0 then raise exception 'Cross-owner read permitted';end if;
  execute 'reset role';
  insert into public.assistant_requests(owner_id,thread_id,message,status,source) values(owner,'approval-sql-test','Failure fixture','processing','coffee_run_diagnostic') returning id into req;
  res=public.coach_finalize_request(owner,req,'awaiting_approval','Test failure','diagnostic_failure','{"summary":"failure"}','[]');
  action=(res->'approval'->>'id')::uuid;h=res->'approval'->>'proposal_hash';
  res=public.coach_decide_action(owner,action,h,'approve');
  if res->>'status'<>'failed' or res->'approval'->>'execution_status'<>'failed' then raise exception 'Failure not recorded';end if;
  insert into public.assistant_requests(owner_id,thread_id,message,status,source) values(owner,'approval-sql-test','Decline fixture','processing','coffee_run_diagnostic') returning id into req;
  res=public.coach_finalize_request(owner,req,'awaiting_approval','Test decline','diagnostic_success','{"summary":"decline"}','[]');
  action=(res->'approval'->>'id')::uuid;h=res->'approval'->>'proposal_hash';
  res=public.coach_decide_action(owner,action,h,'decline');
  res=public.coach_decide_action(owner,action,h,'approve');
  if res->'approval'->>'status'<>'declined' or (res->'approval'->>'execution_attempts')::int<>0 then raise exception 'Declined executed';end if;
  insert into public.assistant_requests(owner_id,thread_id,message,status,source) values(owner,'approval-sql-test','Blocked fixture','processing','coffee_run') returning id into req;
  res=public.coach_finalize_request(owner,req,'awaiting_approval','Proposed email','send_email','{"summary":"no executor"}','[]');
  action=(res->'approval'->>'id')::uuid;h=res->'approval'->>'proposal_hash';
  res=public.coach_decide_action(owner,action,h,'approve');
  if res->'approval'->>'execution_status'<>'blocked' or (res->'approval'->>'execution_attempts')::int<>0 then raise exception 'Unsupported executor ran';end if;
  insert into public.assistant_requests(owner_id,thread_id,message,status,source) values(owner,'approval-sql-test','Expiry fixture','processing','coffee_run_diagnostic') returning id into req;
  res=public.coach_finalize_request(owner,req,'awaiting_approval','Test expired','diagnostic_success','{"summary":"expired"}','[]');
  action=(res->'approval'->>'id')::uuid;h=res->'approval'->>'proposal_hash';
  update public.assistant_actions set expires_at=now()-interval '1 minute' where id=action;
  res=public.coach_decide_action(owner,action,h,'approve');
  if res->'approval'->>'status'<>'expired' or (res->'approval'->>'execution_attempts')::int<>0 then raise exception 'Expired executed';end if;
end $$;
select 'approval SQL assertions passed; fixtures rolled back' as result;
rollback;
